return {
   'svampkorg/moody.nvim',
   event = { 'ModeChanged', 'BufWinEnter', 'WinEnter' },
   dependencies = {
      'catppuccin/nvim',
      'kevinhwang91/nvim-ufo',
   },
   opts = {
      blends = {
         normal = 0.2,
         insert = 0.2,
         visual = 0.25,
         command = 0.2,
         operator = 0.2,
         replace = 0.2,
         select = 0.2,
         terminal = 0.2,
         terminal_n = 0.2,
      },
      colors = {
         normal = '#00BFFF',
         insert = '#4A4B7A',
         visual = '#AD6FF7',
         command = '#EB788B',
         operator = '#FF8F40',
         replace = '#E66767',
         select = '#AD6FF7',
         terminal = '#4CD4BD',
         terminal_n = '#00BBCC',
      },
      disabled_filestypes = { 'TelescopePrompt' },
      disabled_buftypes = {},
      bold_nr = true,
      recording = {
         enabled = false,
         icon = '󰑋',
         pre_registry_text = '[',
         post_registry_text = ']',
         right_padding = 2,
      },
      extend_to_linenr = true,
      extend_to_linenr_visual = false,
      reduce_cursorline = false,
      fold_options = {
         enabled = false,
         start_color = '#C1C1C1',
         end_color = '#2F2F2F',
      },
   },
}
