---@diagnostic disable: duplicate-set-field, need-check-nil, param-type-mismatch, assign-type-mismatch, redundant-parameter, cast-local-type, missing-parameter
local util = require 'azure_pr.util'

describe('util.parse_remote', function()
  local function expect(url, org, project, repo, base)
    eq({ organization = org, project = project, repository = repo, base_url = base }, util.parse_remote(url), url)
  end

  it('parses dev.azure.com https', function()
    expect('https://dev.azure.com/myorg/MyProject/_git/my-repo', 'myorg', 'MyProject', 'my-repo', 'https://dev.azure.com')
  end)

  it('parses dev.azure.com https with user and .git suffix', function()
    expect('https://myorg@dev.azure.com/myorg/MyProject/_git/my-repo', 'myorg', 'MyProject', 'my-repo', 'https://dev.azure.com')
    expect('https://myorg@dev.azure.com/myorg/MyProject/_git/my-repo.git\n', 'myorg', 'MyProject', 'my-repo', 'https://dev.azure.com')
  end)

  it('url-decodes segments', function()
    expect('https://dev.azure.com/myorg/My%20Project/_git/My%20Repo', 'myorg', 'My Project', 'My Repo', 'https://dev.azure.com')
  end)

  it('uses repo as project when project segment is missing', function()
    expect('https://dev.azure.com/myorg/_git/Solo', 'myorg', 'Solo', 'Solo', 'https://dev.azure.com')
  end)

  it('parses ssh.dev.azure.com', function()
    expect('git@ssh.dev.azure.com:v3/myorg/My%20Project/repo', 'myorg', 'My Project', 'repo', 'https://dev.azure.com')
    expect('ssh://git@ssh.dev.azure.com/v3/myorg/proj/repo', 'myorg', 'proj', 'repo', 'https://dev.azure.com')
  end)

  it('parses visualstudio.com https', function()
    expect('https://myorg.visualstudio.com/Proj/_git/repo', 'myorg', 'Proj', 'repo', 'https://myorg.visualstudio.com')
    expect('https://myorg.visualstudio.com/DefaultCollection/Proj/_git/repo', 'myorg', 'Proj', 'repo', 'https://myorg.visualstudio.com')
    expect('https://user@myorg.visualstudio.com/Proj/_git/repo', 'myorg', 'Proj', 'repo', 'https://myorg.visualstudio.com')
  end)

  it('parses vs-ssh.visualstudio.com', function()
    expect('myorg@vs-ssh.visualstudio.com:v3/myorg/Proj/repo', 'myorg', 'Proj', 'repo', 'https://myorg.visualstudio.com')
  end)

  it('rejects non-azure remotes', function()
    eq(nil, util.parse_remote 'git@github.com:user/repo.git')
    eq(nil, util.parse_remote 'https://github.com/user/repo')
    eq(nil, util.parse_remote '')
    eq(nil, util.parse_remote(nil))
    eq(nil, util.parse_remote 'https://dev.azure.com/myorg/proj')
  end)
end)

describe('util.url_encode', function()
  it('keeps unreserved and encodes the rest', function()
    eq('a-b_c.d~e', util.url_encode 'a-b_c.d~e')
    eq('My%20Project', util.url_encode 'My Project')
    eq('%24top', util.url_encode '$top')
    eq('a%2Fb', util.url_encode 'a/b')
    eq('42', util.url_encode(42))
    eq('%C5%BC', util.url_encode 'ż')
  end)
end)

describe('util.parse_date', function()
  it('parses Azure timestamps as UTC', function()
    eq(0, util.parse_date '1970-01-01T00:00:00Z')
    eq(1704164645, util.parse_date '2024-01-02T03:04:05.1234567Z')
    eq(1704164645, util.parse_date '2024-01-02T03:04:05Z')
    eq(1704164645, util.parse_date '2024-01-02T03:04:05')
    eq(951782400, util.parse_date '2000-02-29T00:00:00Z')
  end)
  it('honours offsets', function()
    eq(1704164645, util.parse_date '2024-01-02T05:04:05.12+02:00')
    eq(1704164645, util.parse_date '2024-01-02T02:04:05-01:00')
  end)
  it('returns nil for invalid or unset dates', function()
    eq(nil, util.parse_date(nil))
    eq(nil, util.parse_date 'garbage')
    eq(nil, util.parse_date '0001-01-01T00:00:00')
  end)
end)

describe('util.relative_time', function()
  local now = 1000000000
  it('formats buckets', function()
    eq('just now', util.relative_time(now - 10, now))
    eq('just now', util.relative_time(now + 100, now))
    eq('2m ago', util.relative_time(now - 125, now))
    eq('5h ago', util.relative_time(now - 5 * 3600 - 5, now))
    eq('3d ago', util.relative_time(now - 3 * 86400, now))
    eq('2mo ago', util.relative_time(now - 65 * 86400, now))
    eq('1y ago', util.relative_time(now - 400 * 86400, now))
    eq('', util.relative_time(nil, now))
  end)
end)

describe('util.format_date', function()
  it('formats with os.date', function()
    eq(os.date('%Y-%m-%d %H:%M', 1704164645), util.format_date(1704164645))
    eq(os.date('%Y', 1704164645), util.format_date(1704164645, '%Y'))
    eq('', util.format_date(nil))
  end)
end)

describe('util.strip_ref', function()
  it('strips refs/heads', function()
    eq('main', util.strip_ref 'refs/heads/main')
    eq('feature/x', util.strip_ref 'refs/heads/feature/x')
    eq('main', util.strip_ref 'main')
    eq(nil, util.strip_ref(nil))
  end)
end)

describe('util.truncate / pad_right', function()
  it('truncates ascii', function()
    eq('hello', util.truncate('hello', 5))
    eq('hel…', util.truncate('hello', 4))
    eq('…', util.truncate('hello', 1))
    eq('', util.truncate('hello', 0))
    eq('', util.truncate(nil, 3))
  end)
  it('truncates multibyte by display width', function()
    eq('zażółć', util.truncate('zażółć', 6))
    eq('zażó…', util.truncate('zażółć gęślą', 5))
    eq(5, vim.fn.strdisplaywidth(util.truncate('zażółć gęślą', 5)))
  end)
  it('handles wide characters', function()
    -- each CJK char is 2 cells wide
    local r = util.truncate('日本語テキスト', 6)
    eq('日本…', r)
    truthy(vim.fn.strdisplaywidth(r) <= 6)
  end)
  it('pads by display width', function()
    eq('ab   ', util.pad_right('ab', 5))
    eq('żó   ', util.pad_right('żó', 5))
    eq('日本 ', util.pad_right('日本', 5))
    eq('toolong', util.pad_right('toolong', 3))
    eq('   ', util.pad_right(nil, 3))
  end)
end)

describe('util.split_lines', function()
  it('normalises line endings', function()
    eq({ 'a', 'b', 'c' }, util.split_lines 'a\r\nb\nc')
    eq({ 'a', '', 'b' }, util.split_lines 'a\r\rb')
    eq({}, util.split_lines '')
    eq({}, util.split_lines(nil))
  end)
end)

describe('util.notify', function()
  it('calls vim.notify with title', function()
    local orig = vim.notify
    local got
    vim.notify = function(msg, level, opts)
      got = { msg, level, opts }
    end
    util.notify('hi', vim.log.levels.WARN)
    vim.notify = orig
    eq({ 'hi', vim.log.levels.WARN, { title = 'Azure PR' } }, got)
  end)
end)
